###
# @name user1
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luis 18",
    "phone": "61982072434",
    "email": "luis18@gmail.com",
    "password":"123456",
    "role": "BARBER"
}

###
# @name loginBarber
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "luis18@gmail.com",
    "password":"123456"
}
###

# @name loginClient
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "luis2@gmail.com",
    "password":"123456"
}

###
# @name getAll
GET http://localhost:3000/users
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyAxOCIsImVtYWlsIjoibHVpczE4QGdtYWlsLmNvbSIsInJvbGUiOiJCQVJCRVIiLCJpYXQiOjE3NDYxOTEwODEsImV4cCI6MTc0NjIwOTA4MSwic3ViIjoiMTUifQ.2JSzAGNqOSG0OyL8wKskj50lE2tHd20ayCKQNAeiPCY

###
# @name getOneUser
GET http://localhost:3000/users/schedule/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyAxOCIsImVtYWlsIjoibHVpczE4QGdtYWlsLmNvbSIsInJvbGUiOiJCQVJCRVIiLCJpYXQiOjE3NDk0ODA1MDEsImV4cCI6MTc0OTQ5ODUwMSwic3ViIjoiMTUifQ.VBgRUX1ysyrSgoAkHylJBa7gYAhUwrNZHiTd5N_ASCU


###
# @name getOneClient
GET http://localhost:3000/users/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyAxOCIsImVtYWlsIjoibHVpczE4QGdtYWlsLmNvbSIsInJvbGUiOiJCQVJCRVIiLCJpYXQiOjE3NDk0ODA1MDEsImV4cCI6MTc0OTQ5ODUwMSwic3ViIjoiMTUifQ.VBgRUX1ysyrSgoAkHylJBa7gYAhUwrNZHiTd5N_ASCU

###
# @name updateUserClient
PATCH http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyAyLjAiLCJlbWFpbCI6Imx1aXMyQGdtYWlsLmNvbSIsInJvbGUiOiJDTElFTlQiLCJpYXQiOjE3NDY0NTAyODEsImV4cCI6MTc0NjQ2ODI4MSwic3ViIjoiMiJ9.Jo4iDdfT2nsP9QsIRZZL1jHiomnoRX_K-tSF3JqXcag

{
    "id": 2,
    "name": "Luis 2.0",
    "phone": "61982072434",
    "email": "luis2@gmail.com"
}

###
# @name updateUser
PATCH http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyAxOCIsImVtYWlsIjoibHVpczE4QGdtYWlsLmNvbSIsInJvbGUiOiJCQVJCRVIiLCJpYXQiOjE3NDYxOTEwODEsImV4cCI6MTc0NjIwOTA4MSwic3ViIjoiMTUifQ.2JSzAGNqOSG0OyL8wKskj50lE2tHd20ayCKQNAeiPCY

{
    "id": 1,
    "name": "Luis",
    "email": "luis@gmail.com"
}