###
# @name user1
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luis 4",
    "phone": "61982072434",
    "email": "luis4@gmail.com",
    "role": "CLIENT"
}

###
# @name loginPartner1
GET http://localhost:3000/users
Content-Type: application/json

###
# @name loginPartner1
GET http://localhost:3000/users/1
Content-Type: application/json


###
# @name updateUser
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
    "id": 2,
    "name": "Luis 2.0",
    "phone": "61982072434",
    "email": "luis2@gmail.com"
}

###
# @name updateUser
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "id": 1,
    "name": "Luis",
    "email": "luis@gmail.com"
}